### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PatheticMustan** [PatheticMustan/ProdigySourceBot#1]
Quick todo:

- [x] Get contents/sha of a certain file

- [x] Update contents of a certain file.

- [x] SetInterval to check for new Prodigy version

- [x] Send message in discord server using a webhook.

- [ ] Get Twitter token

- [ ] Send tweet using bot.

**Comment by ghost** [comment]
just saying (i saw this bot [in my feed](https://prnt.sc/v5dybz))

> Send message in Discord server using bot

just use a webhook ngl

**Comment by PatheticMustan** [comment]
;((

Okie

**Comment by ashtoncoded** [comment]
IS IT HERE

**Comment by PatheticMustan** [comment]
nope, good guess :D
